mongock:
  migration-scan-package:
    - io.mongock.examples.mongodb.springboot.advance.migration
  track-ignored: true
  transaction-enabled: true
  runner-type: InitializingBean
  mongo-db:
    read-concern: local




